# Generated by Django 5.1 on 2024-08-16 16:58

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the category', max_length=100, unique=True)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='category')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the product', max_length=100, unique=True)),
                ('image', models.FileField(blank=True, default='product.jpg', null=True, upload_to='product')),
                ('description', models.TextField(blank=True, help_text='Description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=12)),
                ('old_price', models.DecimalField(decimal_places=2, help_text='Old Price of the product', max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping amount', max_digits=12)),
                ('stock_qty', models.IntegerField(help_text='Stock of the product')),
                ('in_stock', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISABLED', 'Disabled'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk1234567890', length=10, max_length=13, prefix='PID', unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
