# Generated by Django 5.1 on 2024-08-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Country',
            new_name='country',
        ),
    ]
