# Generated by Django 5.1 on 2024-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_color_product_alter_gallery_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=1, help_text='Discount'),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='answer',
            field=models.TextField(blank=True, help_text='Answer', null=True),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='question',
            field=models.CharField(help_text='Question', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=None, help_text='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, help_text='Reply', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(help_text='Review'),
        ),
    ]
