# Generated by Django 5.1 on 2024-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cart_user_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the product', max_length=100, null=True),
        ),
    ]
